#pragma config(Sensor, dgtl1,  EncoderVal,     sensorQuadEncoder)
#pragma config(Motor,  port1,           shift,         tmotorNone, openLoop)
#pragma config(Motor,  port2,           right,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           right2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           left2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          turn,          tmotorVex269_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void roboturn()
{
	int driver = -(SensorValue[EncoderVal] * (127/210));
	motor[turn] = (vexRT[Ch1] - driver);
}

task main()
{
	int driveval = 0, turnval = 0;
	while (1)
	{
		if (abs(vexRT[Ch3]) > 15) driveval = vexRT[Ch3];
		else driveval = 0;
		if (abs(vexRT[Ch1]) > 15) turnval = -vexRT[Ch1];
		else turnval = 0;

		motor[turn] = turnval;
		//roboturn();
		if (vexRT[Btn8U] == 1) SensorValue[EncoderVal] = 0;
		motor[left] = driveval;
		motor[left2] = driveval;
		motor[right] = driveval;
		motor[right2] = driveval;

		if (vexRT[Btn5U] == 1) motor[shift] = -127;
		else if (vexRT[Btn6U] == 1) motor[shift] = 127;
		else motor[shift] = 0;
	}
}
