#pragma config(Motor,  port1,           Claw,          tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LowerGearBoxL, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           UpperGearBoxTL, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LeftDrive,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           UpperGearBoxTR, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           UpperGearBoxBR, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RightDrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           UpperGearBoxBL, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LowerGearBoxR, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          Claw2,         tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"

void launch(int speed, int type)//launch at 40% speed of lower gear box to go up, 30% to go down
{
	int speeds;
	if (type == 0)
	{
		if (speed < 0) speeds = speed * .2;
		else speeds = speed * .4;
		motor[LowerGearBoxL] = speed;
		motor[LowerGearBoxR] = speed;
		motor[UpperGearBoxBL] = speeds;
		motor[UpperGearBoxBR] = speeds;
		motor[UpperGearBoxTL] = speeds;
		motor[UpperGearBoxTR] = speeds;
	}
	else if (type == 1)
	{
		motor[UpperGearBoxBL] = speed;
		motor[UpperGearBoxBR] = speed;
		motor[UpperGearBoxTL] = speed;
		motor[UpperGearBoxTR] = speed;
	}

}

void clawOC(int speed)
{
	motor[Claw] = speed;
	motor[Claw2] = speed;
}

void pre_auton()
{

}

task autonomous()
{

}

task usercontrol()
{
	int threshold = 15;
	int driveval = 0, turnval = 0;
	int throwtype = 0;
	while (1)
	{

		if (abs(vexRT[Ch3]) > threshold) driveval = vexRT[Ch3];
		else driveval = 0;
		if (abs(vexRT[Ch1]) > threshold) turnval = vexRT[Ch1];
		else turnval = 0;

		motor[LeftDrive] = driveval + turnval;
		motor[RightDrive] = driveval - turnval;

		if (vexRT[Btn8DXmtr2] == 1)
		{
			while (vexRT[Btn8DXmtr2] == 1){}
			throwtype = 1 - throwtype;
		}

		if (abs(vexRT[Ch3Xmtr2]) > threshold) launch(vexRT[Ch3Xmtr2], throwtype);
		else launch(0, 0);

		if (vexRT[Btn5UXmtr2] == 1) motor[Claw2] = 127/2;
		else if (vexRT[Btn6UXmtr2] == 1) motor[Claw] = 127/2;
		else if (abs(vexRT[Ch2Xmtr2]) > threshold) clawOC(vexRT[Ch2Xmtr2]);
		else clawOC(0);
	}
}
